### ISSUE TITLE
Error loading JSON-LD in insecure mode

### ISSUE THREAD

**Issue by harlantwood** [citizencode/trust-exchange#18]
Currently when running:

```
bin/trust claim   --creator did:00a65b11-593c-4a46-bf64-8b83f3ef698f   --target did:59f269a0-0847-4f00-8c4c-26d84e6714c4   --description 'Elixir programming'   --value 0.99   --algorithm EcdsaKoblitzSignature2016   --private-key L4mEi7eEdTNNFQEWaa7JhUKAbtHdVvByGAqvpJKC53mfiqunjBjw 
```

I get: 

```
jsonld.NormalizeError: Could not convert input to RDF dataset before normalization.
    at /Users/harlan/code/trust-exchange/node_modules/jsonld/js/jsonld.js:806:25
    at /Users/harlan/code/trust-exchange/node_modules/jsonld/js/jsonld.js:952:14
    at /Users/harlan/code/trust-exchange/node_modules/jsonld/js/jsonld.js:326:16
    at Array.done (/Users/harlan/code/trust-exchange/node_modules/jsonld/js/jsonld.js:6848:20)
    at /Users/harlan/code/trust-exchange/node_modules/jsonld/js/jsonld.js:1557:21
    at loadDocument (/Users/harlan/code/trust-exchange/node_modules/jsonld/js/jsonld.js:1781:14)
    at ._loader (/Users/harlan/code/trust-exchange/node_modules/jsonld/js/jsonld.js:1769:5)
    at jsonld.RequestQueue.add (/Users/harlan/code/trust-exchange/node_modules/jsonld/js/jsonld.js:1553:10)
    at jsonld.loadDocument (/Users/harlan/code/trust-exchange/node_modules/jsonld/js/jsonld.js:1234:24)
    at /Users/harlan/code/trust-exchange/node_modules/jsonld/js/jsonld.js:6878:23
```

In debug mode, I found it was trying to load something within the jsonld node module from an HTTP url, while in secure mode.

If I hack into `./node_modules/jsonld-signatures/lib/jsonld-signatures.js` and change `secure: true` to `secure: false`:

```js
        libs[name].useDocumentLoader('node', {secure: false, strictSSL: true});
```

It "works" fine.  

Um, correction, it did a minute ago, but stopped working when I reinstalled node modules, then did the tweak again.

All of the links to and within schemas ( https://github.com/CoMakery/trust-exchange-schema ) are https.  Not sure what the problem is here.

**Comment by harlantwood** [comment]
Working fine now, maybe the schema was cached...
